#!/bin/bash

# General
export GS_DEFAULT_REMOTE='origin'
export GS_GIT_STORY_BRANCH='master' # Default target for 'dev' & 'done' commands
export GS_TEST_ON_AUTO_MERGE=true

# Tests
export GS_PRE_COMMIT_HOOK

# Project integration
export GS_PACKAGE
export GS_RELEASE
export GS_INSTALL
export GS_PRODUCTION_BRANCH='heads/master'
export GS_NEXT_VERSION_BRANCH
export GS_EDGE_BRANCH



# Done
export GS_PRINT_CHECKLIST=false
export GS_PROMPT_ON_DONE=false
export GS_LOCAL_MERGE=false
export GS_TEST_ON_DONE=true

# Project Website
export GS_HAS_GITHUB=true
export GS_PROJECT_URL # No need to setup if project hosted on Github. If set it overrides GitHub path.


# Prompts
export GS_CHECKLIST_MESSAGE="
Checklist:
\t 1. Have you written tests?
\t 2. Do all tests pass?
\t 3. Have you refactored your code?
\t 4. Are you ready for possible merge conflicts?"

export GS_NEW_TAG_PROMPT="What tag would you like to give this version?"


# git-story
export GS_GIT_STORY_EXT_BRANCH='master' # Target branch for updating the git-story tool
