#!/bin/bash
source $GS_INIT_PATH
__git-story-init

##########
#  done  #
##########

usage() {
  __gs-print "
usage:
\t git done
only if all changes have been committed.
otherwise run:
\t git done 'Commit message' <target_branch>
will fetch and merge <target_branch>. <target_branch> is optional and defaults to $GS_GIT_STORY_BRANCH.
note:"
  __gs-warning "\t Can cause merge conflicts"
}

__gs-print-merged-run-hook-message() {
  __gs-info "Remote changes from '$1' merged."
  __gs-info "Running pre-commit hook."
}

main() {
  if [[ "$1" == "--usage" ]]; then
    usage
    return
  fi

  __gs-precommit-hook

  if [[ $GS_PRINT_CHECKLIST == true ]]; then
    __gs-ready-checklist-print
    confirm_message="Have you answered yes to all of the above?"
  else
    confirm_message="Are your sure?"
  fi

  __gs-print ""

  if [[ $GS_PRINT_CHECKLIST != true ]] && [[ $GS_PROMPT_ON_DONE  == false ]]; then
    gs-ready-execute "$@"
  else
    while true; do
      if [[ $SHELL == "/bin/zsh" ]]; then
        yn=""
        vared -p "$confirm_message (y\n)" yn
      else
        read -p "$confirm_message  (y\n)" yn
      fi
      case $yn in
        [Yy]* ) gs-ready-execute "$@"; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
      esac
    done
    return
  fi
}

gs-ready-execute() {
  if [[ $(git status 2> /dev/null | tail -n1) != *"working directory clean"* ]]; then
    if [[ -z "$1" ]]; then
      __gs-error "You have uncommited changes you must provide a commit message."
      return
    fi
    git add --all
    git commit -m "$1"
  elif [[ ! -z "$1" ]]; then
    __gs-warning "Nothing to commit. Ignoring arguments."
  fi
  # Update current branch
  local current="$(git rev-parse --abbrev-ref HEAD)"
  # Pull from remote
  __gs-info "\nPull from: '$current'"
  pull_tail=$(git pull origin $current 2> /dev/null | tail -n1)
  if [[ $pull_tail == *"Automatic merge failed"* ]]; then
   __gs-automatic-merge-failed $current $current
   return
  elif [[ $pull_tail == *"Already up-to-date"* ]]; then
    __gs-info "'$current' already up-to-date."
  else
    __gs-print "[gs] pull_tail: $pull_tail"
    __gs-print-merged-run-hook-message $current
    __gs-precommit-hook
    if [[ ! -z $GS_PRE_COMMIT_HOOK ]]; then
      while true; do
        if [[ $SHELL == "/bin/zsh" ]]; then
          yn=""
          vared -p "$confirm_message (y\n)" yn
        else
          read -p "Did all tests pass? (y\n)" yn
        fi
        case $yn in
          [Yy]* ) __gs-success "Resuming.."; break;;
          [Nn]* ) __gs-warning "Aborted."; return; break;;
          * ) echo "Please answer yes or no.";;
        esac
      done
    fi
  fi
  __gs-print "\n[push]"
  git push origin $current

  # Update target branch
  local target=${2:-master}
  # Pull from remote
  __gs-print "\nPull from: '$target'"
  target_pull_tail=$(git pull origin $target 2> /dev/null | tail -n1)
  if [[ $target_pull_tail == *"Automatic merge failed"* ]]; then
   __gs-automatic-merge-failed $target $current
   return
  elif [[ $target_pull_tail == *"Already up-to-date"* ]]; then
    __gs-print "'$target' already up-to-date."
  else
    __gs-print "[gs] pull_tail: $target_pull_tail"
    __gs-print-merged-run-hook-message $target
    __gs-precommit-hook
    if [[ ! -z $GS_PRE_COMMIT_HOOK ]]; then
      while true; do
        if [[ $SHELL == "/bin/zsh" ]]; then
          yn=""
          vared -p "$confirm_message (y\n)" yn
        else
          read -p "Did all tests pass? (y\n)" yn
        fi
        case $yn in
          [Yy]* ) __gs-success "Resuming.."; break;;
          [Nn]* ) __gs-warning "Aborted."; return; break;;
          * ) echo "Please answer yes or no.";;
        esac
      done
    fi
  fi
  __gs-info "\n[push]"
  git push origin $current # Push merged updates from target branch to current

  __gs-print ""
  __gs-success "Successfully merged remote '$target' branch and pushed '$current' to remote."
  __gs-print ""

  if [[ $GS_PROMPT_BROWSE_URL == true ]]; then
    local prompt_message="Would you like to open your projects website? (y\n)"
    while true; do
      if [[ $SHELL == "/bin/zsh" ]]; then
        yn=""
        vared -p "$prompt_message" yn
      else
        read -p "$prompt_message" yn
      fi
      case $yn in
        [Yy]* ) git browse; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
      esac
    done
  fi
}

main "$@"
