#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "usage:
\t git update <branch>
Pull updates from specified branch from remote.
If no branch is given it will default to the current branch.
Assumes GS_DEFAULT_ORIGIN as remote."
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  current_branch=$(__gs-current-branch)
  __gs-print "Pulling updates from: $current_branch"
  git pull $GS_DEFAULT_REMOTE $current_branch
}

main "$@"
