#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage(){
  __gs-print "
usage:
\t git git-story-update <target_branch>
updates git-story.
<target_branch> is optional and defaults to master.
"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  target=${1-$GS_GIT_STORY_BRANCH}
  __gs-print "Downloading latest changes made to 'git-story' from branch: '$target'"
  current_dir=$(pwd)
  cd $HOME/.git-story && git pull origin $target
  cd $current_dir
  __gs-success "Successfully updated git-story."
}

main "$@"
