#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
To set global pre-commit command edit ~/.git-story/config.sh.

To set project specific pre-commit command create '.gitstoryrc' at git root.
See ~/.git-story/config for available config options."
}

main() {
  if [[ "$1" == "--usage" ]]; then
    usage
    return
  fi

  if [[ ! -z $GS_PRE_COMMIT_HOOK ]]; then
    __gs-info "Running pre-commit hook."
    eval $GS_PRE_COMMIT_HOOK
    __gs-info "Ran all tests. Check status."
  else
    __gs-print "No pre-commit-hook set. Skipping..."
  fi
}

main "$@"
