#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<extension-name>

required:
  extension-name

example:
  git gs-extend awesome-extension
will make it possible to run:
  git awesome-extension

Creates a new file with specified name in $GS_EXENSIONS_FOLDER."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  local new_cmd_name=$(__gs-not-null-or-prompt "$1" "Specify new command name: ")
  __gs-no-spaces-or-die "$new_cmd_name" "Command name"

  full_script_path="$GS_EXENSIONS_FOLDER/git-$new_cmd_name"
  command_template=$(cat $GS_FOLDER/docs/new-extension-template)
  echo "$command_template" > $full_script_path
  __gs-print "Copied new extension template to $full_script_path"
  __gs-print "Making script executable."
  chmod +x $full_script_path && \
  __gs-success "Added command." || __gs-warn-make-executable
  __gs-info "Edit extension at: $full_script_path"
  __gs-print "You can test your command by running:"
  __gs-print " $ git $new_cmd_name"
}

__gs-warn-make-executable() {
  __gs-warning "Could not make file executable." && \
  __gs-print "Please run \n $ sudo chmod +x $full_script_path"
}

main "$@"
