#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "usage:
\t git redo-commit
Redo last commit."
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  git commit --amend
}

main "$@"
