#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<branch-name>

required:
  branch-name

Create a new branch and push it to remote."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  local branch=$1
  git push $GS_DEFAULT_REMOTE HEAD:refs/heads/$branch && \
  git fetch $GS_DEFAULT_REMOTE && \
  git branch --track $branch $GS_DEFAULT_REMOTE/$branch && \
  cd . && \
  git checkout $branch
}

main "$@"
