#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<commit-msg>

optional:
  commit-msg, default: open default git editor

Commit all files and push current branch."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ $(__gs-is-clean-dir) == "dirty" ]]; then
    git addcom "$1"
  fi
  local branch=$(__gs-current-branch)
  git pull $GS_DEFAULT_REMOTE $branch
  git push $GS_DEFAULT_REMOTE $branch
}

main "$@"
