#!/bin/bash
# Original: https://github.com/visionmedia/git-extras/blob/master/bin/git-summary

source $GS_INIT_PATH
__git-story-init

USAGE="<commit-sha>

optional:
  commit-sha, default: current commit

Show project summary."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  commit=""
  test $# -ne 0 && commit=$@
  project=${PWD##*/}

  # summary
  echo
  echo " project  : $project"
  echo " repo age :" $(repository_age)
  echo " active   :"  $(active_days) days
  echo " commits  :" $(commit_count)
  if test "$commit" = ""; then
    echo " files    :" $(file_count)
  fi
  echo " authors  : "
  authors
  echo
  git line-summary --with-out-summary
}

main "$@"
