#!/bin/bash
source $GS_INIT_PATH
__git-story-init

#########
#  dev  #
#########

USAGE="<branch-name> <target-branch>

required:
  branch-name

optional:
  target-branch, default: $GS_GIT_STORY_BRANCH

Creates a new branch branch-name from newest version of target-branch."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  local new_branch="$1"
  local target_branch_arg="$2"

  if [[ -z "$new_branch" ]]; then
    __gs-error "Missing required argument <branch_name>"
    usage
    die
  fi

  __gs-dir-clean-or-die
  __gs-no-spaces-or-die "$new_branch"
  __gs-no-spaces-or-die "$target_branch_arg"

  local target_branch=${target_branch_arg:-$GS_GIT_STORY_BRANCH}
  gs-validate-branch-params "$new_branch" "$target_branch"

  local merge_err_msg="$(gs-print-dev-merge-conflict $new_branch $target_branch)"
  __gs-pull-and-check-status $target_branch $target_branch "$merge_err_msg"

  __gs-dir-clean-or-die
  git create-branch $new_branch

  __gs-success "Success"
  __gs-print "Updated$PURPLE $target_branch$RESET, from repository."
  __gs-print "Created branch: $PURPLE $new_branch $RESET"
  __gs-print "Based on branch:$PURPLE $target_branch $RESET"
}

gs-validate-branch-params() {
  local new_branch="$1"
  local target_branch="$2"
  git fetch $GS_DEFAULT_REMOTE
  __gs-global-unique-branch-or-die $new_branch
  __gs-branch-exists-or-die $target_branch
}

gs-print-dev-merge-conflict() {
  local new_branch="$1"
  local target_branch="$2"
  echo "You have a conflict in your target branch: $target_branch.
Beware of the changes you commit in this branch.

You have three options:

  1. Fix the merge conflict locally.
    $ git addcom 'Fixed merge conflicts'
    $ git feature $new_branch $target_branch

  2. Fix the merge conflict and push to remote (BEWARE)
    $ git finish
    $ git feature $new_branch $target_branch

  3. Abort the merge and choose antother target branch.
    $ git abort-merge
    $ git feature $new_branch <other_branch>

Beware of the changes that you make to the target branch.
Especially if its an integration branch e.g master."
}

main "$@"
