#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<opts>

Add --with-out-summary to print without project summary."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {

  project=${PWD##*/}

  #
  # list the last modified author for each line
  #
  function single_file {
    while read data
    do
    if [[ $(file $data) = *text ]]; then   #
        git blame --line-porcelain $data | sed -n 's/^author //p';
      fi
    done
  }

  #
  # list the author for all file
  #
  function lines {
    git ls-files | single_file
  }

  #
  # count the line count
  #
  function count {
    lines | wc -l
  }

  #
  # sort by author modified lines
  #
  function authors {
    lines | sort | uniq -c | sort -rn
  }

  #
  # list as percentage for author modified lines
  #
  function result {
    authors | awk '
      { args[NR] = $0; sum += $0 }
      END {
      printf " %-9s: %i\n", "lines", sum
      printf " %-9s: \n", "authors"
        for (i = 1; i <= NR; ++i) {
          printf " %-30s %2.1f%%\n", args[i], 100 * args[i] / sum
        }
      }
      '
  }

  # summary
  if [[ $1 != --with-out-summary ]]; then
    echo
    echo " project  : $project"
  fi
  result
  echo

}

main "$@"

