#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="

opens current project's repository page."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ ! -z "$1" ]]; then
    __gs-ignore-args "git browse"
  fi

  # Check path
  if [[ ! -z $GS_PROJECT_URL ]]; then
    local url=$GS_PROJECT_URL
  elif [[ $GS_HAS_GITHUB == true ]]; then
    local url=$(git remote -v | grep git@github.com | grep fetch | head -1 | cut -f2 | cut -d' ' -f1 | sed -e's/:/\//' -e 's/git@/http:\/\//')
  fi

  # Check OS
  if [[ "$(uname -s)" == "Linux" ]]; then
    xdg-open "$url" &
  elif [ "$(uname)" == "Darwin" ]; then
    open "$url" &
  elif [ "$(expr substr $(uname -s) 1 6)" == "CYGWIN" ]; then
    cygstart "$url" &
  fi
}

main "$@"
