#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<pull_request_id> <branch_name>

Fetch and checkout GitHub pull request to new branch."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  local pr_id=$(__gs-not-null-or-prompt "$1" "Specify new branch name: ")
  local branch=$(__gs-not-null-or-prompt "$2" "Specify new branch name: ")

  if [[ -z "$pr_id" ]]; then
    __gs-error "Missing required argument <pull_request_id>"
  fi

  if [[ -z "$branch" ]]; then
    __gs-error "Missing required argument <branch_name>"
  fi

  git fetch origin pull/$pr_id/head:"$2"
}

main "$@"
