#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "usage:
\t git release
Runs GS_RELEASE command, if specified.
"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ ! -z $GS_RELEASE ]]; then
    __gs-info "Packaging project."
    eval $GS_RELEASE
    __gs-info "Done"
  else
    __gs-warning "No release command set in .gitstoryrc"
  fi
}

main "$@"
