#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="

Tag the current commit and push it to remote."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  git fetch --tags
  __gs-print "Previous releases:"
  __gs-print "========================"
  git tag --list -n
  __gs-print "========================"

  __gs-print "Parent tag and current commit:"
  __gs-info "$(git describe)"
  local prompt_text="What tag would you like to give this version? "
  local version_no="$(__gs-prompt-for-result "$prompt_text")"

  if [[ -z $version_no ]]; then
    __gs-error "ERROR:"
    __gs-print "\t Tag can *not* be empty"
    die
  elif [[ "$version_no" == *" "* ]]; then
    __gs-error "ERROR:"
    __gs-print "\t Tag can *not* contain spaces!"
    die
  fi

  if [[ $GS_SIGN_RELEASE == true ]]; then
    local sign_opt_string='--sign'
  else
    local sign_opt_string='--annotate'
  fi

  local release_title="$(__gs-prompt-for-result "Provide release title: ")"
  local tag_message="Version $version_no"
  if [[ ! -z $release_title ]]; then
    tag_message="$tag_message - $release_title"
  fi
  git tag $sign_opt_string $version_no --message="$tag_message" && \
  git push --tags && \
  __gs-success "Success." && __gs-print "Tagged version: $version_no" || \
  __gs-error "Something went wrong creating the tag."
}

main "$@"
