#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "usage:
\t git churn
Show churn for whole repo.

Show churn for specific directories:
\t git churn app lib

Show churn for a time range:
\t git churn --since='1 month ago'

Any standard arguments to 'git log' are OK."
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  # Written by Corey Haines
  # Scriptified by Gary Bernhardt
  git log --all -M -C --name-only --format='format:' "$@" | sort | grep -v '^$' | uniq -c | sort | awk 'BEGIN {print "count,file"} {print $1 ", " $2}'
}

main "$@"
