#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<number>

required:
  number

the number of commits you'd like to squash together."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ -z $1 ]]; then
    __gs-error "Missing required argument <number>"
    die
  fi
  local squash_number=$1
  __gs-continue-prompt "Are you sure you want to squash together the last $squash_number commits?"
  git reset --soft HEAD~$squash_number && git commit
}

main "$@"
