#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="

List repository commits and branch network."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  git log $1 --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"
}

main "$@"
