#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<branch-name>

required:
  branch-name

Deletes branch branch-name from local and remote."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  git push $GS_DEFAULT_REMOTE :refs/heads/$1 && \
  git remote prune $GS_DEFAULT_REMOTE && \
  git branch -D $1
}

main "$@"
