#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<diff_string>

Compare two branches, tags, commits.

example:
  git diff-commits master...v1.1.0"

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  local differ_string=$1
  git log   \
    --graph \
    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' \
    --abbrev-commit \
    --date=relative $differ_string
}

main "$@"
