#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
usage:
\t git abort-merge
aborts current merge.
"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ ! -z "$1" ]]; then
    __gs-print-args-ignored
  fi
  git merge --abort && __gs-success "Successfully aborted merge." || __gs-warning "No merge to abort."
}

main "$@"
