#!/bin/bash
# Original: https://github.com/visionmedia/git-extras/blob/master/bin/git-local-commits
source $GS_INIT_PATH
__git-story-init

USAGE="

Show local commits that haven't been pushed to remote."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  local ref=$(git symbolic-ref HEAD)
  local branch=${ref#refs/heads/}
  git log origin/${branch}..${branch} $*
}

main "$@"
