#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "usage:
\t git addcom <commit_msg>
Adds all in project files and commits them.
<commit_msg> is optional."
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  __gs-add-all
  if [[ -z $1 ]]; then
    git commit
  else
    git commit -m "$1"
  fi
}

main "$@"
