#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<branch-name>

required:
  branch-name

change the current workspace to branch-name."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  __gs-dir-clean-or-die
  git checkout $1
}

main "$@"
