#!/bin/bash
# Original: https://github.com/visionmedia/git-extras/blob/master/bin/git-rename-tag
source $GS_INIT_PATH
__git-story-init

USAGE="<old-tag> <new-tag>

required:
  old-tag
  new-tag

Renames a given tag."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  local old=$(__gs-not-null-or-prompt "$1" "Specify old tag name: ")
  local new=$(__gs-not-null-or-prompt "$2" "Specify new tag name: ")

  git tag $new $old
  git tag --delete $old
  git push origin $new
  git push origin :refs/tag/$old
}

main "$@"
