#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<args>

Show the diff of everything you haven't pushed yet."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  branch=$(git rev-parse --abbrev-ref HEAD)
  git diff origin/$branch..HEAD
}

main "$@"
