#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage(){
  __gs-print "usage:
\t git gs-update <target_branch>
updates git-story.
<target_branch> is optional and defaults to master."
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  local target=${1-$GS_GIT_STORY_EXT_BRANCH}
  __gs-print "Downloading latest changes made to 'git-story' from branch: '$target'"
  cd $HOME/.git-story && \
  git pull origin $target && \
  __gs-success "Successfully updated git-story." || \
  __gs-error "Something went wrong."
}

main "$@"
