#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "Usage:
\t git release
Runs GS_RELEASE command, if specified.
"
}

main() {
  if [[ "$1" == "--usage" ]]; then
    usage
    return
  fi
  if [[ ! -z $GS_RELEASE ]]; then
    __gs-info "Packaging project."
    eval $GS_RELEASE
    __gs-info "Done"
  fi
}

main "$@"
