#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "usage:
\t git todos
Lists all TODOS and FIXMES."
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
 local default_path='*'
 local search_path="${1:-$default_path}"
 __gs-info "TODOS:"
 full-text-search-project 'TODO\|todo.*' $search_path
 __gs-print
 __gs-info "FIXMES:"
 full-text-search-project 'FIXME\|fixme.*' $search_path
}

full-text-search-project() {
  grep --line-number --recursive --binary-file=without-match "$@"
}

main "$@"
