#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
usage:
\t git conflicted
Lists all filenames that has merge conflicts.
"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  filenames="$(grep -rl "<<<<<<< HEAD" *)"
  number_of_files=$(echo $filenames | wc -w 2> /dev/null)
  if [[ $number_of_files -eq 0 ]]; then
    __gs-success "No conflicting files."
  else
    __gs-print "$filenames"
    __gs-warning "Conflicting files: $number_of_files"
  fi
}

main "$@"
