#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<path>

optional:
  path, default: *

Lists all filenames in path that has merge conflicts."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  filenames="$(grep --recursive --files-with-matches "<<<<<<< HEAD" *)"
  local number_of_files=$(echo $filenames | wc -w 2> /dev/null)
  if [[ $number_of_files -eq 0 ]]; then
    __gs-success "No conflicting files."
  else
    __gs-info "Merge conflicts in:"
    __gs-print "$filenames"
    __gs-warning "Conflicting files: $number_of_files"
  fi
}

main "$@"
