#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="

Lists all git-story extensions to git."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  __gs-print-command-list
}

main "$@"
