#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<branch-name>

required:
  branch-name

Will refuse to delete all integration branches defined in gitstoryrc.
Deletes branch branch-name from local and remote."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  branch="$1"
  if [[ -z $branch ]];then
    __gs-error "Missing required argument <branch_name>"
    die
  fi
  __gs-no-spaces-or-die "$branch"

  integration_branches=($GS_GIT_STORY_BRANCH $GS_PRODUCTION_BRANCH $GS_NEXT_VERSION_BRANCH $GS_EDGE_BRANCH)

  for inbranch in ${integration_branches[*]}; do
    local ibranch=${inbranch/heads\//}
    if [[ $ibranch == $branch ]]; then
      __gs-print "Wont delete integration branch '$ibranch'. Skipping..."
      die
    fi
  done

  __gs-print "Deleting branch: '$branch'"
  git branch -D $branch
  git branch -d -r origin/$branch
  git push origin :refs/heads/$branch
}

main "$@"
