#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<args>

Show the diffstat of everything you haven't pushed yet."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  branch=$(git rev-parse --abbrev-ref HEAD)
  count=$(git rev-list --count HEAD origin/$branch...HEAD)

  if [ "$count" -eq "1" ]
  then
    s=''
  else
    s='s'
  fi

  git diff --stat origin/$branch..HEAD
  echo " $count commit$s total"
}

main "$@"
