#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="

Runs GS_PACKAGE command, if specified."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ ! -z $GS_PACKAGE ]]; then
    __gs-info "Packaging project."
    eval $GS_PACKAGE "$@"
    __gs-info "Done"
  else
    __gs-warning "No package command set in .gitstoryrc"
  fi
}

main "$@"
