#!/bin/bash
# Original: https://github.com/visionmedia/git-extras/blob/master/bin/git-archive-file

source $GS_INIT_PATH
__git-story-init

USAGE="

Create zip-file of project."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  # extract current branch name
  BRANCH=$(git name-rev HEAD 2> /dev/null | awk "{ print \$2 }")

  # get name of the most top folder of current directory, used for the
  # output filename
  ARCHIVE_NAME=$(basename $(pwd))

  if [[ $BRANCH = tags* ]]; then
  	BRANCH=$(git describe)
  	echo Building for tag \"$BRANCH\"
  	FILENAME=$ARCHIVE_NAME.$BRANCH.zip
  else
  	echo Building archive on branch \"$BRANCH\"
  	# get a version string, so archives will not be overwritten when creating
  	# many of them
  	VERSION=$(git describe --always --long)
  	# if not on master append branch name into the filename
  	if [ "$BRANCH" = "master" ]; then
  		FILENAME=$ARCHIVE_NAME.$VERSION.zip
  	else
  		FILENAME=$ARCHIVE_NAME.$VERSION.$BRANCH.zip
  	fi
  fi

  # combine path and filename
  OUTPUT=$(pwd)/$FILENAME

  # building archive
  git archive --format zip --output $OUTPUT $BRANCH

  # also display size of the resulting file
  echo Saved to \"$FILENAME\" \(`du -h $OUTPUT | cut -f1`\)
}

main "$@"
