#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "usage:
\t git fuckit <message>
Commit all files with optional <message> and push current branch.
Default is to prompt for commit message"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ $(__gs-is-clean-dir) == "dirty" ]]; then
    git addcom "$1"
  fi
  git push $GS_DEFAULT_REMOTE $(__gs-current-branch)
}

main "$@"
