#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "usage:
\t git goto <branch_name>
change the current workspace to <branch_name>"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  __gs-dir-clean-or-die
  git checkout $1
}

main "$@"
