#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<args>

Undo your last commit, but don't throw away your changes"

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  git reset --soft HEAD^
}

main "$@"
