#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
usage:
\t gs open
opens current project page
alias: pull-request, github"
}

main() {
  if [[ $1 == "--usage" ]]; then
    usage
    return
  elif [[ ! -z "$1" ]]; then
    __gs-ignore-args "gs open"
  fi

  # Check path
  if [[ ! -z $GS_PROJECT_URL ]]; then
    url=$GS_PROJECT_URL
  elif [[ $GS_HAS_GITHUB == true ]]; then
    url=$(git remote -v | grep git@github.com | grep fetch | head -1 | cut -f2 | cut -d' ' -f1 | sed -e's/:/\//' -e 's/git@/http:\/\//')
  fi

  # Check OS
  if [[ "$(uname -s)" == "Linux" ]]; then
    xdg-open $url &
  elif [ "$(uname)" == "Darwin" ]; then
    open $url &
  fi
}

main "$@"
