#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
usage:
\t git fetch-branches
fetches all branches at remote.
"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ ! -z $1 ]]; then
    __gs-ignore-args "git fetch-branches"
  fi
  git fetch $GS_DEFAULT_REMOTE
  __gs-info "Fetching all branches."
  for remote in `git branch --remote | grep -v "\->" 2> /dev/null`; do
    __gs-fetch-remote-branch ${remote//origin\//} &
  done
  __gs-info "Fetched all branches."
}

__gs-fetch-remote-branch() {
  git fetch $GS_DEFAULT_REMOTE $1 2> /dev/null || __gs-warning "Fetch of '$1' failed."
}

main "$@"
