#!/bin/bash
# Original source: http://chneukirchen.org/blog/archive/2013/01/a-grab-bag-of-git-tricks.html

source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
usage:
\t git neck [-r] [COMMIT]
show commits until first branching point
"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  [ "$1" = -r ] && shift && R=-r
  COMMIT=$(git rev-parse --no-flags --default HEAD "$@")
  # skip first elements of trail
  TORSO=$(git trail $R $COMMIT | cut -d' ' -f2 | uniq | sed -n 2p)
  # fall back to initial commit on empty trail
  : ${TORSO:=$(git rev-list --max-parents=0 HEAD)}
  git log --oneline $(git rev-parse --no-revs "$@") $COMMIT...$TORSO
}

main "$@"
