#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="

Runs GS_DEPLOY command, if specified."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  if [[ ! -z $GS_DEPLOY ]]; then
    __gs-info "Deploying project."
    eval $GS_DEPLOY
    __gs-info "Done"
  else
    __gs-warning "No deploy command set in .gitstoryrc"
  fi
}

main "$@"
