#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<commit-msg>

optional:
  commit-msg, default: open default git editor

Adds all in project files and commits them.
Will open default git-editor if commit-msg is not provided."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  __gs-add-all
  if [[ -z $1 ]]; then
    git commit
  else
    git commit -m "$1"
  fi
}

main "$@"
