#!/bin/bash
# Original: https://github.com/visionmedia/git-extras/blob/master/bin/git-commits-since
source $GS_INIT_PATH
__git-story-init

USAGE="<time>

optional:
  time, default: 'last week'

examples:
  $ git commits-since 'yesterday'
  $ git commits-since 'last 2 days'
  $ git commits-since 'last month'
  $ git commits-since 'last 2 months'

show commits since <time>."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  SINCE="last week"
  test $# -ne 0 && SINCE=$@
  echo "... commits since $SINCE" >&2
  git log --pretty='%an - %s' --after="@{$SINCE}"
}

main "$@"
