#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="

Push current branch to remote."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  git push $GS_DEFAULT_REMOTE $(__gs-current-branch)
}

main "$@"
