#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<path>

optional:
  path, default: *

Lists all TODOS and FIXMES."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
 local default_path='*'
 local search_path="${1:-$default_path}"
 local todo_results="$(find-matching-lines 'TODO\|TODO:' $search_path)"
 local fixme_results="$(find-matching-lines 'FIXME\|FIXME:' $search_path)"
__gs-info "TODOS:"
 __gs-print "$todo_results"
 __gs-print
__gs-info "FIXMES:"
 __gs-print "$fixme_results"
 __gs-info "\nFound:"

 print-count "$todo_results" "TODOS"
 print-count "$fixme_results" "FIXMES"
}

print-count() {
  local res="$1"
  local type="$2"
  if [[ "$res" == "" ]];then
    __gs-print "       0 $type"
  else
    __gs-print "$(echo "$res" | wc -l) $type"
  fi
}

find-matching-lines() {
  echo "$(grep                \
              --word-regexp   \
              --with-filename \
              --line-number   \
              --recursive     \
              --binary-file=without-match "$@" \
          | cut -d":" -f1-2)"
}

main "$@"
