#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="[options] [<path>]

optional:
  [options], all standard arguments to 'git log' are OK.

Show churn for whole repo:
  git churn

Show churn for specific directories:
  git churn app lib

Show churn for a time range:
  git churn --since='1 month ago'

List all files and how many times they've been modified, sorted by number of modifications."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  # Written by Corey Haines
  # Scriptified by Gary Bernhardt
  git log --all -M -C --name-only --format='format:' "$@" | \
    sort | grep -v '^$' | uniq -c | sort | \
    awk 'BEGIN {print "count,file"} {print $1 ", " $2}'
}

main "$@"
