#!/bin/bash
# Orginal: https://github.com/visionmedia/git-extras/blob/master/bin/git-ignore

source $GS_INIT_PATH
__git-story-init

USAGE="[<context>] [<pattern> [<pattern>]...]

optional:
  context, default: --local
  pattern, default: ''

context: --local, --global

Add and list patterns to local and global gitignore."

# TODO: Enhance to be used with language specific gitingores,
#       available at https://github.com/github/gitignore‎

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  function show_contents {
    test -f "$2" && echo "$1 gitignore: $2" && cat "$2"
  }

  function show_global {
    show_contents Global `git config --global core.excludesfile`
  }

  function add_global {
    add_patterns `git config --global core.excludesfile` "$@"
  }

  function show_local {
    show_contents Local .gitignore
  }

  function add_local {
    add_patterns .gitignore "$@"
  }

  function add_patterns {
    echo "Adding pattern(s) to: $1"
    for pattern in "${@:2}"; do
      echo "... adding '$pattern'"
      (test -f "$1" && test "$pattern" && grep -q "$pattern" "$1") || echo "$pattern" >> "$1"
    done
  }


  if test -z $1; then
    show_local
  else
    case "$1" in
      -l | --local)
        test $# -gt 1 && add_local "${@:2}" && echo
        show_local
        ;;
      -g | --global)
        test $# -gt 1 && add_global "${@:2}" && echo
        show_global
        ;;
      *)
        add_local "$@"
        ;;
    esac
  fi
}

main "$@"
