#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
usage:
\t gs list-extended
Lists all git-story commands.
"
}

main() {
  if [[ "$1" == "--usage" ]]; then
    usage
    return
  fi
  __gs-print-command-list
}

main "$@"
