#!/bin/bash
GIT_STORY_URL="https://github.com/buren/git-story.git"

install-git-story() {
  if [[ ! -d $HOME/.git-story/ ]]; then
    current_folder=$(pwd)
    cd $HOME && \
    git clone --depth=1 $GIT_STORY_URL && \
    mv git-story .git-story || echo "Something went wrong."
    cd $current_folder
    echo "Making ~/.git-story/src/git/* executable"
    chmod +x $HOME/.git-story/src/git/*
  else
    echo "git-story already installed"
    echo "Exiting"
    return
  fi

  if [[ -f $HOME/.bash_profile ]]; then
    echo "Injecting import: ~/.bash_profile"
    cat $HOME/.git-story/setup/import_install >> $HOME/.bash_profile
  elif [[ -f $HOME/.bashrc ]]; then
    echo "Injecting import: ~/.bashrc"
    cat $HOME/.git-story/setup/import_install >> $HOME/.bashrc
  elif [[ -f $HOME/.zshrc ]]; then
    echo "Injecting import: ~/.zshrc"
    cat $HOME/.git-story/setup/import_install >> $HOME/.zshrc
  else
    echo "[ERROR] Neither .bash_profile, .bashrc or .zshrc found."
    echo ""
    echo -e "To install add the below line to your bash profile."
    echo -e "\t source ~/.git-story/setup/import"
  fi
  echo "Installed."
  echo "Please reload your shell to enable git-story extensions."
}

install-git-story
