#!/bin/bash

###################################
# example of complete .gitstoryrc #
###################################

# NOTE:
#
# Write any bash script here and it will be
# source'd before each git-story command.
#
# But the file's intended purpose is to provide
# project specific version controlled configuration
# of git-story
#

# Any value *not* specified in this file will use
# it's default value defined in
# ~/.git-story/config

enduro_package="bash $HOME/apps/maven/apache-maven-3.0-SNAPSHOT/bin/mvn clean package"

# Define what branch to update git-story from
GS_GIT_STORY_BRANCH='custom-git-story-branch'

# Default remote for git-story extensions
GS_DEFAULT_REMOTE='origin'
# Default target branch for 'dev' & 'done' commands
GS_GIT_STORY_BRANCH='master'

# Tests
# git-story will eval any string in GS_PRE_COMMIT_HOOK
GS_PRE_COMMIT_HOOK="bash $HOME/apps/maven/apache-maven-3.0-SNAPSHOT/bin/mvn clean test"

# General
# Run test command on automatic merge
GS_TEST_ON_AUTO_MERGE=true

# Project integration
# git-story will eval any string in GS_PACKAGE
GS_PACKAGE="$enduro_package"
# git-story will eval any string in GS_RELEASE
GS_RELEASE="$enduro_package && bash release.sh"
# git-story will eval any string in GS_INSTALL
GS_INSTALL="curl https://raw2.github.com/buren/enduro/master/install_enduro.sh | bash"
# used to indentify integration branches for branch-status command
# see src/git-branch-status for details
GS_PRODUCTION_BRANCH='heads/master'
GS_NEXT_VERSION_BRANCH=''
GS_EDGE_BRANCH=''

# Done
# print checklist before executing done command
GS_PRINT_CHECKLIST=true
# prompt before executing done command, ignored if checklist is true
GS_PROMPT_ON_DONE=true
# merge feature branch with target branch locally and push it after done command
GS_LOCAL_MERGE=false
# Run tests before done command
GS_TEST_ON_DONE=true

# Project Website
GS_HAS_GITHUB=false
# If project is not hosted on GitHub provide address to the reposiory
GS_PROJECT_URL="https://github.com/buren/enduro" # has same effect as GS_HAS_GITHUB=true in this case

# Prompts
# Checklist thats printed before executing done command (respects the value of GS_PRINT_CHECKLIST)
GS_CHECKLIST_MESSAGE="
Checklist:
\t 1. Have you written tests?
\t 2. Do all tests pass?
\t 3. Have you refactored your code?
\t 4. Are you ready for possible merge conflicts?"
