#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
usage:
\t git <new-command>
Description goes here...
"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  # Add execution code here
}

main "$@"
