#!/bin/bash
source $GS_INIT_PATH
__git-story-init

usage() {
  __gs-print "
usage:
\t git NEWCOMMANDNAME
Description goes here...
"
}

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  __gs-info "TODO:$RESET Add code to: $(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`" # Remove this line
  # Add execution code here
  # ...
}

main "$@"
