#!/bin/bash
source $GS_INIT_PATH
__git-story-init

USAGE="<args>

Description goes here..."

main() {
  __gs-check-usage-param $1
  main-exec "$@"
}

main-exec() {
  __gs-info "TODO:$RESET Add code to: $(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/`basename "${BASH_SOURCE[0]}"`" # Remove this line
  # Add execution code here
  # ...
}

main "$@"
