#!/bin/bash

######################
#  git-story export  #
######################

export GS_FOLDER="$HOME/.git-story"
export GS_INIT_PATH=$GS_FOLDER/src/git-story
export GS_EXENSIONS_FOLDER=$GS_FOLDER/src/git

####################
#  git-story init  #
####################

# Called from each extension
__git-story-init() {
  set -e
  # Read default config
  source $HOME/.git-story/config
  # Import common functionality
  for file in $GS_FOLDER/src/common/*; do
    source $file
  done
  # Read project specific config
  __gs-read-project-config
  cd "$(__gs-git-root-dir)"
  . "$(git --exec-path)/git-sh-setup"
}

__gs-print-command-list() {
  echo "$(cat $HOME/.git-story/docs/command_list.txt)"
}


####################
#  git-story help  #
####################

gs-help() {
  __gs-print-command-list
  echo "Run git-story extension command followed by '--usage' for command details."
}


###################
#  git-story cli  #
###################

git-story() {
  if [[ -z $1 ]] || [[ "$1" == "--usage" ]] || [[ "$1" == "--list" ]] || \
    [[ "$1" == "-h" ]] || [[ "$1" == "-help" ]] || [[ "$1" == "--help" ]]; then
    gs-help
  elif [[ "$1" == "update" ]]; then
    git gs-update $2
  elif [[ "$1" == "extend" ]]; then
    git gs-extend $2
  else
    echo "Unknown command '$1'"
  fi
}
