#!/bin/bash

###########
#  messages   #
###########

__gs-uncommitted-changes-message() {
  __gs-warning "
You have uncommitted changes.
Please commit or stash your changes.
"
}

__gs-automatic-merge-failed() {
  __gs-print "Automatic merge with branch '$1' into '$2' failed."
  __gs-error "Merge with '$1' failed."
  __gs-info "Please fix all conflicts and then run 'gs finish'."
}

__gs-print-args-ignored() {
  __gs-info "Function does not take arguments. Ignoring..."
}

##########
#  help  #
##########

__gs-print-command-list() {
  __gs-print "$(cat $HOME/.git-story/docs/command_list.txt)"
}

__gs-done-checklist-print() {
  __gs-warning "$GS_CHECKLIST_MESSAGE"
  echo ""
}
